### ISSUE TITLE
Path("\\")

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/fa19-516-155#1]
although you may be in windows, but shuld we not use Path("/") to be portable on linux first. should that not also be \\ in windows?

I suggest to first use linux path syntax and have pathlib convert it to windows where needed

**Comment by kpimparkar** [comment]
.replace("\\"."/") was added just to ensure that storage providers receive the path in linux syntax even from a windows machine. 
Working on usage of pathlib.Path instead of .replace in this case.

**Comment by laszewsk** [comment]
do we need also \\, / ?

**Comment by kpimparkar** [comment]
Hi Professor, 
Changes have been made to use linux path syntax. Code is modified so that both, Linux and Windows path syntax are correctly interpreted. 
Due to this, any command in following syntax work ok:

cms transfer list --target=local:
cms transfer list --target=local:'\~/cmStorage/a'
cms transfer list --target=local:"\~\\cmStorage\\a"

Thanks for catching this issue.
